config/routes.rb
Openhat::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users ,  :controllers => { :registrations => 'registrations' } do
    get "/register"   => "registrations#new",   :as => :new_user_registration
    get "/login", :to => "devise/sessions#new"
  end

  match 'profile' => 'home#profile', :as => 'profile'
  match 'profile/:id' => 'home#public_profile', :as => 'public_profile'
  match 'profile_modal/:id' => 'home#public_profile_modal', :as => 'public_profile_modal'
  match 'accounts_settings' => 'home#accounts_settings', :as => 'accounts_settings'
  match 'follow/:id' => 'home#follow', :as => 'follow'
  match 'unfollow/:id' => 'home#unfollow', :as => 'unfollow'
  match 'messages' => 'messages#index', :as => 'messages'
  match 'messages/new.:format' => 'messages#user_ajax'
  match 'message/send' => 'messages#sendto', :via => "post"
  match 'message/send_m' => 'messages#send_m', :via => "post"
  match 'stage/create' => 'stages#create', :via => "post"
  match 'message_new' => 'messages#new', :as => 'message_new'
  match 'message/:id' => 'messages#read', :as => 'message_read'
  match 'avatar/maker' => 'avatars#index', :as => 'avatar_maker'
  match 'avatar/getSections/:id' => 'avatars#getSections'
  match 'avatar/getSectionUrl/:id' => 'avatars#getSectionUrl'
  match 'create_performance' => 'stages#makeStage', :as => 'create_performance'
  match 'stage' => 'stages#index'
  match 'stage/:id' => 'stages#index', :as => 'stage'
  match 'stage2/:id' => 'stages#index2', :as => 'stage2'
  match 'category/:id' => 'categories#index', :as => 'category'
  match 'all' => 'categories#all', :as => 'all'
  match '/pages/:page' => "pages#page", :as => 'pages'
  match '/pages/:page/modal' => "pages#modal", :as => 'page_modal'
  match 'buy_tokens' => "tokens#buy", :as => 'buy_tokens'
  match 'buy_show' => "tokens#show"
  match 'buy_cancel' => "tokens#cancel"
  match 'send_tips/:id/:stage'  => "tokens#send_tips", :as => 'send_tips'
  match 'send_heckle'  => "tokens#send_heckle", :as => 'send_heckle'
  match 'sendtip' => "tokens#sendtip"
  match 'changeimage' => "home#changeimage"
  match 'report/:id' => "stages#report"
  match 'share/:id' => "home#share"
  match 'close/:id' => "stages#close"
  match 'configuration/:id' => "stages#configuration"
  match 'saveconfiguration/:id/:option' => "stages#saveconfiguration"
  match 'tippers/:id' => 'stages#tippers'
  match 'totaltips/:id' => 'stages#totaltips'
  match 'savecharacter' => "home#savecharacter", :as => 'savecharacter', :via => 'post'
  match 'saveinformation' => "home#saveinformation", :as => 'saveinformation', :via => 'post'
  match 'saveprivacy' => "home#saveprivacy", :as => 'saveprivacy', :via => 'post'

  match 'saveimage' => "home#saveimage", :as => 'saveimage', :via => 'post'

  match 'savereport/:id/:report/:sender' => 'stages#savereport', :as => 'savereport'
  match 'buy/:heckle/:tokens/:amount' => "tokens#buytokens"
  match 'buystage/:stage/:item/:tokens' => "tokens#buystages"
  match 'discountHeckle/:heckle' => 'tokens#discountHeckle'
  match 'beta' => 'home#beta'
  match 'contact' => "pages#contact", :as => 'contact', :via => 'post'

  match 'shop_add' => 'shopping#add', :as => 'shop_add', :via => 'post'
  match 'cashout' => 'home#cashout'

  match  'performance_update/:id' => 'stages#performance_update'
  match 'send_cashout/:user/:tokens' => 'home#send_cashout'
  match 'featured_users/:id' => 'stages#featured_users'
  match 'payment/notify' => 'tokens#notify', :via => 'post'
  match 'noinvitation' => 'stages#noinvitation', :as => 'noinvitation'
  match 'invitation/:id' => 'stages#invitation', :as => 'invitation'
  match 'add_invitation/:id/:email' => 'stages#add_invitation', :email => /.*/
  match 'noticket' => 'stages#noticket', :as => 'noticket'
  match 'notification' => 'messages#notification'
  root :to => 'home#index'

  match 'shopping_cart' => 'shopping#shopping_cart'
  match 'upload_dropbox' => 'home#upload_dropbox'











end

app/controllers/home_controller.rb
#require 'ostruct'
#require 'money'
#require 'active_merchant'
#require 'active_merchant/billing/integrations/action_view_helper'
class HomeController < ApplicationController
  #include ActiveMerchant::Billing::Integrations
  #ActionView::Base.send(:include,ActiveMerchant::Billing::Integrations::ActionViewHelper)
    def index

        fuu = Stage.find(:all, :conditions => ['delete_status = 0'])
        fuu.each do |ohhfuck|
          t = ohhfuck.updated_at + 20.minutes
          if t <= DateTime.now
            ohhfuck.delete_status = 1
            ohhfuck.save!
          end
        end


        @last_users = User.find(:all, :conditions => ['sign_in_count > 0'], :order => 'created_at DESC')
        @performance = Stage.find(:all, :limit => 3, :order => 'id DESC', :conditions =>['delete_status = 0'])
        @performance_random = Stage.find(:all, :limit => 5, :order => 'rand()', :conditions =>['delete_status = 0'])
    end
    
    def profile
      if current_user
          @followers = Follower.find(:all, :conditions => ['leader = ?', Digest::MD5.hexdigest(current_user.id.to_s)])
          #@activities = Activity.find(:all, :conditions => ['user_id = ?', current_user.id])
          @avatar = Avatar.find(:first, :conditions => ['user_id = ?', current_user.id ])
          @stage = Stage.find(:first, :conditions => ['user_id = ? AND status = "enabled"', current_user.id])
          @character = Character.find(:all, :conditions => ['user_id = ?', current_user])

          tokens = MyToken.find(:all, :conditions => ['user_id = ?',current_user.id])
          @t = 0
          tokens.each do |d|
            if d.operation.nil?
              @t += d.amount.to_i
            else
              @t -= d.amount.to_i
            end
          end

      else
        flash[:notice] = "error 403" 
        redirect_to root_url
      end 
    end
    
    def public_profile
        if current_user 
          if Digest::MD5.hexdigest(current_user.id.to_s) == params[:id]
            redirect_to profile_url
          end
        else
         
        end   
        @user = User.find(:first, :conditions =>['MD5(id) = ?', params[:id]])
        @followers = Follower.find(:all, :conditions => ['leader = ?', params[:id]])
        @activities = Activity.find(:all, :conditions => ['md5(user_id) = ?', params[:id]])
        @avatar = Avatar.find(:first, :conditions => ['md5(user_id) = ?', params[:id] ])
        @character = Character.find(:all, :conditions => ['user_id = ?', params[:id]])
        #@stage = Stage.find(:first, :conditions => ['user_id = ? AND status = "enabled"', current_user.id])
    end

    def public_profile_modal
      @user = User.find(:first, :conditions =>['id = ?', params[:id]])
      @followers = Follower.find(:all, :conditions => ['leader = ?', params[:id]])
      @activities = Activity.find(:all, :conditions => ['user_id = ?', params[:id]])
      @avatar = Avatar.find(:first, :conditions => ['user_id = ?', params[:id] ])
      @character = Character.find(:all, :conditions => ['user_id = ?', Digest::MD5.hexdigest(params[:id].to_s)])
      render :layout => false
    end

    def follow
        if current_user
          f = Follower.new
          f.leader = params[:id]
          f.user_id = current_user.id
          f.save!
          #flash[:notice] = "Add Follower #" + params[:id].to_s
        else
          #flash[:notice] = "error 403"
        end

        render :text => 'follow'
    end
    
    def unfollow
        if current_user
          Follower.delete_all(['user_id = ? AND leader = ?', current_user.id, params[:id]])  
          flash[:notice] = "unfollow #" + params[:id].to_s
        else
          flash[:notice] = "error 403" 
        end

        render :text => 'unfollow'
    end
    def accounts_settings
      if current_user
        @character = Character.find(:all, :conditions => ['user_id = ?', current_user])
        @tokens = Token.find(:all)
        @stage_item = StageItem.find(:all, :conditions => ['user_id = ?', current_user.id])
        @performance_random = Stage.find(:all, :limit => 5, :order => 'rand()', :conditions =>['delete_status = 0'])

        _user = {:first_name => "saran", :last_name => "v", :email => "some_per@gmail.com", :address1 => "awesome ln", :city => "Austin", :state => "TX", :zip => "78759", :country => "USA", :phone => "5120070070" }

        tokens = MyToken.find(:all, :conditions => ['user_id = ?',current_user.id])
        @t = 0
        tokens.each do |d|
          if d.operation.nil?
            @t += d.amount.to_i
          else
            @t -= d.amount.to_i
          end

        end

        #using openstruct to access the hash by a dot notation
        @user = OpenStruct.new _user
        @currency = "USD"
        #a random invoice number for test.

        n = Order.new
        n.user_id = current_user.id
        n.save!

        @invoice = n.id

      else
        flash[:notice] = "error 403"
        redirect_to root_url
      end
    end

    def changeimage

      render :layout => false
    end

    def savecharacter
      if current_user

          Character.delete_all(['user_id = ?', current_user.id])
          params[:data].each do |d|
            p = Character.new
            p.section = d
            p.user_id = current_user.id
            p.save!
          end

          render :text => 'character save'
      else
          render :text => 'error 403'
      end
    end

    def saveinformation
      if current_user
          p = User.find(current_user.id)
          if params[:user][:image].nil?
              p.update_attributes({:name => params[:user][:name], :about => params[:user][:about], :gender => params[:user][:gender], :interest => params[:user][:interest], :hometown => params[:user][:hometown], :birthdate => params[:user][:birthdate] })
          else
              p.update_attributes({:name => params[:user][:name],:image => params[:user][:image], :about => params[:user][:about], :gender => params[:user][:gender], :interest => params[:user][:interest], :hometown => params[:user][:hometown], :birthdate => params[:user][:birthdate] })
          end

          session[:save] =  'Your changes have been save'
          redirect_to accounts_settings_url
      else
          redirect_to accounts_settings_url
      end
    end

    def saveprivacy

      if current_user
        f = Privacy.new
        f.user_id = current_user.id
        f.option1 = params[:privacy][:option1]
        f.option2 = params[:privacy][:option2]
        f.option3 = params[:privacy][:option3]
        f.option4 = params[:privacy][:option4]
        f.option5 = params[:privacy][:option5]
        f.option6 = params[:privacy][:option6]
        f.save!


        session[:saveprivacy] =  'Your changes have been save'
        redirect_to '/accounts_settings#privacy'
      else
        redirect_to '/accounts_settings#privacy'
      end

    end


  def share
    @id =  params[:id]
    render :layout => false
  end

  def saveimage


    p = User.find(current_user.id)
    p.update_attributes({:image => params[:imagen], :image_fb => '' })


    render :layout => false
  end


  def cashout
    tokens = MyToken.find(:all, :conditions => ['user_id = ?',current_user.id])
    @t = 0
    tokens.each do |d|
      if d.operation.nil?
        @t += d.amount.to_i
      else
        @t -= d.amount.to_i
      end

    end
    render :layout => false
  end

  def send_cashout
      mn = MoneyReturn.new
      mn.user_id =  params[:user]
      mn.tokens = params[:tokens]
      mn.status = 0
      mn.date_return = Date.new(Date.today.year,Date.today.mon, -1)
      mn.save!
      render :text => ''
  end


  def beta

    render :layout => false
  end

  def upload_dropbox


     
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/beta.html.erb
<link href="http://fonts.googleapis.com/css?family=Amatic+SC:400,700" media="all" rel="stylesheet" type="text/css"
      xmlns="http://www.w3.org/1999/html">

<style>
    .box-fr{
        font-family: 'Amatic SC', cursive;
        font-weight: 800;
    }
    p{
        font-size: 25px;
    }

</style>
<div class="box-fr">

  <p>Hi, thanks for trying out The Open Hat. We are in a very early stage of development so don't be surprised if some features don't work as expected.</p>
  <p>Please have fun, invite your friends and we really appreciate any <a href="/pages/contact" target="_parent">feedback</a> you can give us.</p>

  <p>Thanks again!</p>

  <p>The Open Hat team</p>



</div>

app/views/home/cashout.html.erb
<script type="text/javascript" src="/javascripts/jquery.min.js"></script>
<script type="text/javascript" >
    $(document).ready(function(){
        $('.button').click(function(){

            if($('.text').val() != ""){
                var request = $.ajax({
                    type: "GET",
                    url: "/send_cashout/<%= current_user.id %>/"+$('.text').val(),
                    success: function(data){
                        alert("Your request has been received");
                        parent.location.reload();
                        //parent.$.fn.colorbox.close();
                    }
                });

            }else{
                alert("Tokens required");
                $('.text').focus();
            }

            return false;
        });
    });
</script>
<link href="http://fonts.googleapis.com/css?family=Amatic+SC:400,700" media="all" rel="stylesheet" type="text/css">
<style>
    .box-fr{
        font-family: 'Amatic SC', cursive;
        font-weight: 800;
    }
    .box-title{
        margin: 0 auto;
        width: 210px;
    }
    .box-title img{
        float: left;
        padding-right: 12px;
    }
    .box-title h2{
        font-size: 38px;
        line-height: 32px;
        margin-left: 12px;
    }
    p{
        font-size: 25px;
        margin: 0px auto;
        width: 440px;
        display: block;
        clear: both;
    }

    p.text-tip{
        color: #D94601;
    }

    a.buy_more{
        color: #D94601;
    }
    .text{
        background: url(/images/img_sprite.png) no-repeat -288px -137px;
        width: 470px;
        height: 63px;
        float: left;
        border: none;
        padding: 4px 8px 6px 14px;
        font-family: 'Amatic SC', cursive;
        font-weight: 800;
        font-size: 30px;
        margin-left: 12px;
    }
    .box-form{
        float:left;
        margin-top: 5px;
        width: 450px;
    }
    .button{
        background: url(/images/img_sprite.png) no-repeat -660px -338px;
        width: 100px;
        height: 49px;
        float: right;
        border: none;
        color: white;
        font-family: 'Amatic SC', cursive;
        font-weight: 400;
        font-size: 17px;
        margin-top: 5px;
    }



</style>
<div class="box-fr">
  <div class="box-title">
    <h2>CASH OUT TOKENS</h2>
  </div>

  <div class="box-form">
    <p>You have <%= @t %> tokens, that's $US <%= ((@t.to_i / 80) * 10).to_f %> , How many tokens do you want to cash out</p>
    <input type="text" name="dolar"  class="text" value="<%= @t %>"  rel="<%= @t %>" />

    <button class="button">Send me the cash</button>

    <p>This payment will be sent to your PayPal account <!-- --> on the "<%= Date.new(Date.today.year,Date.today.mon, -1).mday  %>" of "<%= Date.new(Date.today.year,Date.today.mon, Date.today.mday).strftime('%B')  %>". </p>
  </div>


</div>

app/views/home/changeimage.html.erb
<script type="text/javascript" src="/javascripts/jquery.min.js"></script>
<script type="text/javascript" >
    $(document).ready(function(){

        $('.text').click(function(){
           $('.imagen').click();
        });
        $('.imagen').change(function(){
            $('.text').val($(this).val());
        });
        $('.button').click(function(){
            $('.frm').submit();
        });
    });
</script>
<link href="http://fonts.googleapis.com/css?family=Amatic+SC:400,700" media="all" rel="stylesheet" type="text/css">
<style>
    .box-fr{
        font-family: 'Amatic SC', cursive;
        font-weight: 800;
    }
    .box-title{
        margin: 0 auto;
        width: 245px;
    }
    .box-title img{
        float: left;
        padding-right: 12px;
    }
    .box-title h2{
        font-size: 38px;
        line-height: 32px;
        margin-left: 12px;
    }
    p{
        font-size: 25px;
        margin: 0px auto;
        width: 440px;
    }

    p.text-tip{
        color: #D94601;
    }

    a.buy_more{
        color: #D94601;
    }
    .text{
        background: url('../images/sprite-forms.png') -12px -73px no-repeat;
        width: 460px;
        border: none;
        height: 62px;
        padding: 0px 5px 0px 0px;
        font-size: 21px;
        margin-bottom: 13px;
        margin-left: 14px;
    }
    .box-form{
        float:left;
        margin-top: 50px;
        width: 450px;
    }
    .button{
        background: url(../images/img_sprite.png) no-repeat -660px -338px;
        width: 100px;
        height: 49px;
        float: right;
        border: none;
        color: white;
        font-family: 'Amatic SC', cursive;
        font-weight: 400;
        font-size: 22px;
        margin-top: 5px;
    }
</style>
<div class="box-fr">
  <div class="box-title">
      <h2>CHANGE PROFILE IMAGE</h2>
  </div>
  <p>Select the image you want to upload, this replaces your current image.</p>

  <div class="box-form">
    <%= form_tag('/saveimage', :method=>'post', :multipart => true, :class => "frm") do %>
    <input type="file" name="imagen" class="imagen" style="display: none;" />
    <% end %>
    <input type="text" name="tip"  class="text" />

    <button class="button">Change!</button>

  </div>


</div>

app/views/home/profile.html.erb
<article id="container">
	<!-- start box -->
    <section class="box">
   		<!-- start left side -->
        <section class="Left-side">
        	<!-- start img-block -->
            <section class="img-block">
            	<a href="/changeimage" class="icon" id="changeImage"><%= image_tag 'ic_image.png', :alt => 'icon' %></a>
				<section class="frame">&nbsp;</section>
                <% if !current_user.image_fb.nil? %>
                    <%= image_tag current_user.image_fb.gsub("square", "large"), :width => 298, :height => 350, :alt => current_user.name %>
                <% else %>
				    <%= image_tag current_user.image('profile'), :width => 298, :height => 350, :alt => current_user.name %>
                <% end %>
            </section>
            <!-- end img-block -->
            <section class="clear"></section>
            <!-- start follow us -->
          	<section class="follow-us">
           		<h3><%= @followers.count%>  followers</h3>
            	<%
					if @followers.count > 0
						@followers.each do |f|
				%>
						<div class="follower">
							<%= link_to(image_tag(f.user.image('thumb'), :alt => f.user.name, :width =>'50'), public_profile_path( Digest::MD5.hexdigest(f.user.id.to_s)))  %>
						</div>
				<% 		end
					else
				%>
				
				<% end %>
            </section>
            <!-- end follow us -->
        </section>
        <!-- end left side -->
        <!-- start right side -->
        <section class="Right-side">
        	<!-- start profile -->
            <section class="profile" rel="<%= current_user.id %>">
              <div style="position: absolute;right: 70px;">
                <%
                   if @character.count == 0
                %>
                    <div class="avatar preview avatar-head-1">
                      <div class="avatar preview avatar-eyes-1"></div>
                      <div class="avatar preview avatar-nose-1"></div>
                      <div class="avatar preview avatar-mouth-1"></div>
                    </div>
                    <div class="avatar preview avatar-jacket-1"></div>
                    <div class="avatar preview avatar-legs-1"></div>
                    <div class="avatar preview avatar-feet-1"></div>

                <% else %>
                    <% @character.each do |d| %>
                        <% dd = d.section.split('-') %>
                        <% if dd[1] == 'head' || dd[1] == 'jacket' || dd[1] == 'legs' || dd[1] == 'feet' %>
                            <div class="avatar preview <%= d.section %>">
                              <% if dd[1] == 'head' %>
                                  <% @character.each do |c| %>
                                      <% dc = c.section.split('-') %>
                                      <% if dc[1] == 'eyes' || dc[1] == 'nose' || dc[1] == 'mouth' %>
                                          <div class="avatar preview <%= c.section %>"></div>
                                      <% end %>
                                  <% end %>
                              <% end %>
                            </div>
                        <% end %>
                    <% end %>



                <% end %>
                <%= link_to '(Edit your avatar)', '/accounts_settings#create_your_character', :class => 'edit_avatar' %>
              </div>
 				<section class="rowline">
                	<h2><%= current_user.name%> <%= link_to '(Edit your profile)', '/accounts_settings#user_information', :class => 'edit_profile' %></h2>
            		<span><img src="images/ic_location.png" width="18" height="27" alt="location">Bristol <img src="images/img_doller.png" width="29" height="23" alt="doller" class="doller"><%= @t %> available tokens <%= link_to '(buy more)', '/accounts_settings#tokens', :title => 'buy more' %></span>
                    <h3>About me</h3>
                    <p><%= current_user.about%> </p>
          		</section>
               <!-- <section class="button"><a href="#" title="follow">follow</a></section>
                <section class="button button2"><a href="#" title="send message">send message</a></section> -->
                <section class="clear"></section>
            </section>
            <!-- end profile -->
            <!-- start activity -->
          	<section class="activity">
           		<h3>Recent activiy</h3>
              	<ul>
                    <%
                       activity = Activity.find(:all, :limit => 5, :conditions => ['user_id = ?', current_user.id])
                       activity.each do |act|
                         sss = Stage.find(:first, :conditions => ['SUBSTR(md5(id),1,11) = ?', act.stage_id ])
                    %>
                        <li>
                          <img src="<%= sss.image(:thumb) %>" width="100" height="75" alt="activity">
                          <span class="date">6 days ago</span>
                          <p><%= act.description.html_safe %></p>
                          <section class="clear"></section>
                        </li>

                    <% end %>


              	</ul>
            </section>
            <!-- end activity -->
      	</section>
        <!-- end right side -->
        <section class="clear"></section>
        <!-- start bottom-link -->

        <!-- end bottom-link -->
    </section>
	<!-- end box -->
</article>

app/views/home/public_profile.html.erb
<article id="container">
  <!-- start box -->
  <section class="box">
    <!-- start left side -->
    <section class="Left-side">
      <!-- start img-block -->
      <section class="img-block">

        <section class="frame">&nbsp;</section>
        <% if !@user.image_fb.nil? %>
            <%= image_tag @user.image_fb.gsub("square", "large"), :width => 298, :height => 350, :alt => @user.name %>
        <% else %>
            <%= image_tag @user.image('profile'), :width => 298, :height => 350, :alt => @user.name %>
        <% end %>
      </section>
      <!-- end img-block -->
      <section class="clear"></section>
      <!-- start follow us -->
      <section class="follow-us">
        <%
            rates = Rate.find(:all, :conditions => ['performer = ?', @user.id])
            rate = 0
            rates.each do |r|

            end

        %>
        <p>Rate this performer <span class="rate" date-rating="<%= rate %>"></span></p>
        <h3><%= @followers.count%>  followers</h3>
        <%
           if @followers.count > 0
             @followers.each do |f|
        %>
                <div class="follower">
                  <%= link_to(image_tag((!f.user.image_fb.nil? && f.user.image_file_size.nil? )? f.user.image_fb: f.user.image('thumb'), :alt => f.user.name, :width => '50'), public_profile_path( Digest::MD5.hexdigest(f.user.id.to_s)))  %>
                </div>
            <% 		end
                       else
            %>

        <% end %>
      </section>
      <!-- end follow us -->
    </section>
    <!-- end left side -->
    <!-- start right side -->
    <section class="Right-side">
      <!-- start profile -->
      <section class="profile">
        <div style="position: absolute;right: 70px;">
          <%
             if @character.count == 0
          %>
              <div class="avatar preview avatar-head-1">
                <div class="avatar preview avatar-eyes-1"></div>
                <div class="avatar preview avatar-nose-1"></div>
                <div class="avatar preview avatar-mouth-1"></div>
              </div>
              <div class="avatar preview avatar-jacket-1"></div>
              <div class="avatar preview avatar-legs-1"></div>
              <div class="avatar preview avatar-feet-1"></div>

          <% else %>
              <% @character.each do |d| %>
                  <% dd = d.section.split('-') %>
                  <% if dd[1] == 'head' || dd[1] == 'jacket' || dd[1] == 'legs' || dd[1] == 'feet' %>
                      <div class="avatar preview <%= d.section %>">
                        <% if dd[1] == 'head' %>
                            <% @character.each do |c| %>
                                <% dc = c.section.split('-') %>
                                <% if dc[1] == 'eyes' || dc[1] == 'nose' || dc[1] == 'mouth' %>
                                    <div class="avatar preview <%= c.section %>"></div>
                                <% end %>
                            <% end %>
                        <% end %>
                      </div>
                  <% end %>
              <% end %>



          <% end %>
        </div>
        <section class="rowline">
          <h2><%= @user.name%></h2>
          <span><% if !@user.hometown.nil? %><%= image_tag 'ic_location.png', :alt => 'location' %><%= @user.hometown%><% end %></span>
          <h3>About me</h3>
          <p><%= @user.about%> </p>
        </section>
        <section class="clear"></section>
        <% if current_user %>
            <% f = Follower.find(:first, :conditions => ['user_id = ? AND leader = ?',current_user.id,Digest::MD5.hexdigest(@user.id.to_s) ]) %>
            <% if f.nil? %>
                <section class="button"><%= link_to 'follow', '#', :class => 'perfomer', :title => Digest::MD5.hexdigest(@user.id.to_s) %></section>
            <% else  %>
                <section class="button"><%= link_to 'unfollow', '#', :class => 'perfomer', :title => Digest::MD5.hexdigest(@user.id.to_s) %></section>
            <% end %>

            <section class="button button2"><a href="#" title="send message">send message</a></section>
            <section class="clear"></section>
        <% end  %>

      </section>
      <!-- end profile -->
      <!-- start activity -->
      <section class="activity">
        <h3>Recent activiy</h3>
        <ul>
          <%
             activity = Activity.find(:all, :limit => 5, :conditions => ['user_id = ?', @user.id])
             activity.each do |act|
               sss = Stage.find(:first, :conditions => ['SUBSTR(md5(id),1,11) = ?', act.stage_id ])
          %>
              <li>
                <img src="<%= sss.image(:thumb) %>" width="100" height="75" alt="activity">
                <span class="date">6 days ago</span>
                <p><%= act.description.html_safe %></p>
                <section class="clear"></section>
              </li>

          <% end %>

        </ul>
      </section>
      <!-- end activity -->
    </section>
    <!-- end right side -->
    <section class="clear"></section>
    <!-- start bottom-link -->

    <!-- end bottom-link -->
  </section>
  <!-- end box -->
</article>

app/views/home/saveimage.html.erb
<link href="http://fonts.googleapis.com/css?family=Amatic+SC:400,700" media="all" rel="stylesheet" type="text/css">
<style>
    .box-fr{
        font-family: 'Amatic SC', cursive;
        font-weight: 800;
    }
    .box-title{
        margin: 0 auto;
        width: 245px;
    }
    .box-title img{
        float: left;
        padding-right: 12px;
    }
    .box-title h2{
        font-size: 38px;
        line-height: 32px;
        margin-left: 12px;
    }
    p{
        font-size: 25px;
        margin: 0px auto;
        width: 440px;
    }

    p.text-tip{
        color: #D94601;
    }

    a.buy_more{
        color: #D94601;
    }


</style>
<div class="box-fr">
  <div class="box-title">
    <h2>CHANGE PROFILE IMAGE</h2>
  </div>
  <p>The image has been changed successfully.</p>
  <script type="text/javascript" >
      top.window.opener.location.reload()
  </script>
</div>