config/routes.rb
Openhat::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users ,  :controllers => { :registrations => 'registrations' } do
    get "/register"   => "registrations#new",   :as => :new_user_registration
    get "/login", :to => "devise/sessions#new"
  end

  match 'profile' => 'home#profile', :as => 'profile'
  match 'profile/:id' => 'home#public_profile', :as => 'public_profile'
  match 'profile_modal/:id' => 'home#public_profile_modal', :as => 'public_profile_modal'
  match 'accounts_settings' => 'home#accounts_settings', :as => 'accounts_settings'
  match 'follow/:id' => 'home#follow', :as => 'follow'
  match 'unfollow/:id' => 'home#unfollow', :as => 'unfollow'
  match 'messages' => 'messages#index', :as => 'messages'
  match 'messages/new.:format' => 'messages#user_ajax'
  match 'message/send' => 'messages#sendto', :via => "post"
  match 'message/send_m' => 'messages#send_m', :via => "post"
  match 'stage/create' => 'stages#create', :via => "post"
  match 'message_new' => 'messages#new', :as => 'message_new'
  match 'message/:id' => 'messages#read', :as => 'message_read'
  match 'avatar/maker' => 'avatars#index', :as => 'avatar_maker'
  match 'avatar/getSections/:id' => 'avatars#getSections'
  match 'avatar/getSectionUrl/:id' => 'avatars#getSectionUrl'
  match 'create_performance' => 'stages#makeStage', :as => 'create_performance'
  match 'stage' => 'stages#index'
  match 'stage/:id' => 'stages#index', :as => 'stage'
  match 'stage2/:id' => 'stages#index2', :as => 'stage2'
  match 'category/:id' => 'categories#index', :as => 'category'
  match 'all' => 'categories#all', :as => 'all'
  match '/pages/:page' => "pages#page", :as => 'pages'
  match '/pages/:page/modal' => "pages#modal", :as => 'page_modal'
  match 'buy_tokens' => "tokens#buy", :as => 'buy_tokens'
  match 'buy_show' => "tokens#show"
  match 'buy_cancel' => "tokens#cancel"
  match 'send_tips/:id/:stage'  => "tokens#send_tips", :as => 'send_tips'
  match 'send_heckle'  => "tokens#send_heckle", :as => 'send_heckle'
  match 'sendtip' => "tokens#sendtip"
  match 'changeimage' => "home#changeimage"
  match 'report/:id' => "stages#report"
  match 'share/:id' => "home#share"
  match 'close/:id' => "stages#close"
  match 'configuration/:id' => "stages#configuration"
  match 'saveconfiguration/:id/:option' => "stages#saveconfiguration"
  match 'tippers/:id' => 'stages#tippers'
  match 'totaltips/:id' => 'stages#totaltips'
  match 'savecharacter' => "home#savecharacter", :as => 'savecharacter', :via => 'post'
  match 'saveinformation' => "home#saveinformation", :as => 'saveinformation', :via => 'post'
  match 'saveprivacy' => "home#saveprivacy", :as => 'saveprivacy', :via => 'post'

  match 'saveimage' => "home#saveimage", :as => 'saveimage', :via => 'post'

  match 'savereport/:id/:report/:sender' => 'stages#savereport', :as => 'savereport'
  match 'buy/:heckle/:tokens/:amount' => "tokens#buytokens"
  match 'buystage/:stage/:item/:tokens' => "tokens#buystages"
  match 'discountHeckle/:heckle' => 'tokens#discountHeckle'
  match 'beta' => 'home#beta'
  match 'contact' => "pages#contact", :as => 'contact', :via => 'post'

  match 'shop_add' => 'shopping#add', :as => 'shop_add', :via => 'post'
  match 'cashout' => 'home#cashout'

  match  'performance_update/:id' => 'stages#performance_update'
  match 'send_cashout/:user/:tokens' => 'home#send_cashout'
  match 'featured_users/:id' => 'stages#featured_users'
  match 'payment/notify' => 'tokens#notify', :via => 'post'
  match 'noinvitation' => 'stages#noinvitation', :as => 'noinvitation'
  match 'invitation/:id' => 'stages#invitation', :as => 'invitation'
  match 'add_invitation/:id/:email' => 'stages#add_invitation', :email => /.*/
  match 'noticket' => 'stages#noticket', :as => 'noticket'
  match 'notification' => 'messages#notification'
  root :to => 'home#index'

  match 'shopping_cart' => 'shopping#shopping_cart'
  match 'upload_dropbox' => 'home#upload_dropbox'











end

app/models/stage.rb
class Stage < ActiveRecord::Base
  attr_accessible :category_id, :language_content, :rate, :room_name, :status, :sub_category_id, :type
  has_attached_file :image, :styles => {:thumb => { :geometry => '241x175>', :quality => 50}},:path => ":rails_root/public/images/stages/:style/:id/:filename", :url => "/images/stages/:style/:id/:filename"
  belongs_to :user
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  
  def index
      if current_user
          if params[:id]
            @stage = Stage.find(:first, :conditions => ['SUBSTR(md5(id),1,11) = ?', params[:id]])
            @chp =   Character.find(:all, :conditions => ['user_id = ?', @stage.user_id])
            @up =   User.find(:first, :conditions => ['id = ?', @stage.user_id])
            @id = params[:id]
            @performance = Stage.find(:all, :limit => 3, :order => 'id DESC', :conditions =>['delete_status  = 0 AND id <> ?', @stage.id])

            @tippers = Tip.find(:all, :conditions => ['stage_id = ?', @id], :group => 'sender', :limit => 4, :order => 'SUM(tokens) DESC', :select => 'sender, SUM(tokens) as tokens')
            @character = Character.find(:all, :conditions => ['user_id = ?', current_user.id])
            @performance_random = Stage.find(:all, :limit => 5, :order => 'rand()', :conditions =>['delete_status = 0 '])
            if @stage.user_id == current_user.id

            else
              if @stage.types == 'public'

              else
                  if @stage.ticket_type == 'free'
                    inv = Invitation.find(:first, :conditions => ['user_id = ? AND SUBSTR(md5(stage_id),1,11) = ?',current_user.email, params[:id] ])
                    if inv.nil?
                      redirect_to noinvitation_url
                    end
                  else
                      ticket = Ticket.find(:first, :conditions => ['user_id = ? AND SUBSTR(md5(stage_id),1,11) = ?',current_user.id, params[:id] ])
                      if ticket.nil?
                        redirect_to noticket_url
                      end

                  end


              end

            end


          else
            flash[:notice] = "error 403"
            redirect_to root_url
          end
      else
          session[:error] = 'You must <a href="/login">login</a> or <a href="/register">register</a> to see this performance.'
          redirect_to root_url
      end
  end
  
  def index2
     if current_user

        @stage = Stage.find(:first, :conditions => ['SUBSTR(md5(id),1,11) = ?', params[:id]])
        @id = params[:id]
        @performance = Stage.find(:all, :limit => 3, :order => 'id DESC', :conditions =>['delete_status  = 0'])
        @tippers = Tip.find(:all, :conditions => ['stage_id = ?', @id], :group => 'sender', :limit => 4, :order => 'SUM(tokens) DESC', :select => 'sender, SUM(tokens) as tokens')
        @character = Character.find(:all, :conditions => ['user_id = ?', current_user.id])
        @performance_random = Stage.find(:all, :limit => 5, :order => 'rand()', :conditions =>['delete_status = 0'])



     end
  end

  def noinvitation

  end

  def invitation
    if current_user
      if params[:id]
        @stage = Stage.find(:first, :conditions => ['SUBSTR(md5(id),1,11) = ?', params[:id]])
        if @stage.user_id == current_user.id
            @id = params[:id]
        else
            redirect_to root_url
        end

      else
        redirect_to root_url
      end
    else
      session[:error] = 'You must <a href="/login">login</a> or <a href="/register">register</a> to see this performance.'
      redirect_to root_url
    end
  end

  def add_invitation
    if params[:id]
      inv = Invitation.new
      inv.stage_id = params[:id]
      inv.user_id = params[:email]
      inv.save!
    end

    render :text => ''
  end

  def noticket

  end


  def makeStage
      if current_user
          @stage_item = StageItem.find(:all, :conditions => ['user_id = ?', current_user.id])
      else
          flash[:notice] = "error 403"
          redirect_to root_url
      end
    
  end

  def create
    if current_user
      if params[:stage]
        @stage = Stage.new
        @stage.types = params[:stage][:type]
        @stage.room_name = params[:stage][:room_name]
        @stage.category_id = params[:stage][:category_id]
        #@stage.sub_category_id = params[:stage][:sub_category_id]
        @stage.language_content = params[:stage][:language_content]
        @stage.rate = params[:stage][:rate]
        @stage.user_id = current_user.id
        @stage.ticket_type = params[:stage][:type_ticket]

        @stage.ticket_price = params[:stage][:ticket_price]
        @stage.limited_seats = params[:stage][:limit_seats]
        @stage.image = params[:stage][:performance_image]
        @stage.design = params[:stage][:design]
        @stage.delete_status = 0
        if params[:stage][:shownow] == "yes"
            @stage.live = DateTime.now
            @stage.status = 'online'
        else

            @stage.live =  DateTime.civil(params[:stage]['live(1i)'].to_i,params[:stage]['live(2i)'].to_i,params[:stage]['live(3i)'].to_i,params[:stage]['live(4i)'].to_i,params[:stage]['live(5i)'].to_i)
            @stage.status = 'offline'
        end


        @stage.design = params[:stage][:design]


        if @stage.save!
          flash[:notice] = "Stage Save!"
          if  params[:stage][:type] == 'private' && params[:stage][:ticket_price] == 'free'
              redirect_to invitation_path(Digest::MD5.hexdigest(@stage.id.to_s)[0,11])
          else
              redirect_to stage_path(Digest::MD5.hexdigest(@stage.id.to_s)[0,11])
          end
          #redirect_to create_performance_url
        end
      end
    else
      flash[:notice] = "error 403"
      redirect_to root_url
    end
  end

  def report
    @id = params[:id]
    render :layout => false
  end

  def savereport

    # params[:id] params[:report] params[:sender]
    re = Report.new
    re.stage = params[:id]
    re.reason = params[:report]
    re.user_id = params[:sender]
    re.save!

    render :text => '0'
  end


  def configuration
    @id = params[:id]
    @stage = Stage.find(:first, :conditions => ['SUBSTR(md5(id),1,11) = ?', params[:id]])
    @stage_item = StageItem.find(:all, :conditions => ['user_id = ?', current_user.id])
    render :layout => false
  end

  def tippers
    @id = params[:id]
    @tippers = Tip.find(:all,:select => 'SUM(tokens) as token, sender', :group => 'sender' , :order => 'token DESC', :conditions => ['stage_id = ?', params[:id]])

    render :layout => false
  end

  def featured_users
    @tippers = Tip.find(:all, :conditions => ['stage_id = ?', params[:id]], :group => 'sender', :limit => 4, :order => 'SUM(tokens) DESC', :select => 'sender, SUM(tokens) as tokens')


    render :layout => false
  end


  def totaltips
    @tippers = Tip.find(:first,:select => 'SUM(tokens) as token', :conditions => ['stage_id = ?', params[:id]])
     render :text => @tippers.token.to_s
  end

  def performance_update
    @stage = Stage.find(:first, :conditions => ['SUBSTR(md5(id),1,11) = ?', params[:id]])
    @stage.updated_at = DateTime.now
    @stage.save!
    render :text => ''
  end


  def saveconfiguration
    @stage = Stage.find(:first, :conditions => ['SUBSTR(md5(id),1,11) = ?', params[:id]])
    @stage.design = params[:option]

    @stage.save!
    render :text => 'save configurarion'
  end
  def close

    if params[:id]
      @stage = Stage.find(:first, :conditions => ['SUBSTR(md5(id),1,11) = ?', params[:id]])
      @stage.delete_status = 1
      if @stage.save!
        session[:error]  = 'Stage Close'
        redirect_to root_url
      end
    else
      redirect_to root_url
    end
  end
end

app/views/stages/configuration.html.erb
<link href="http://fonts.googleapis.com/css?family=Amatic+SC:400,700" media="all" rel="stylesheet" type="text/css">
<script src="/javascripts/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $('.button').click(function(){
            parent.$(parent.document).trigger("ChangeBackground", [$('.design:checked').val(), '<%= @id %>']);
            return false;
        });

    });

</script>

<style>
    .box-fr{
        font-family: 'Amatic SC', cursive;
        font-weight: 800;
    }
    .box-title{
        margin: 0 auto;
        width: 235px;
    }
    .box-title img{
        float: left;
        padding-right: 12px;
    }
    .box-title h2{
        font-size: 33px;
        line-height: 14px;
        margin-left: 12px;
    }
    p{
        font-size: 21px;
        margin: 0px auto;
        width: 440px;
        margin-top: -10px;
        padding: 0px;
    }

    p.text-tip{
        color: #D94601;
    }

    a.buy_more{
        color: #D94601;
    }
    .text{
        background: url('../images/sprite-forms.png') -17px -221px no-repeat;
        width: 339px;
        border: none;
        height: 62px;
        padding: 0px 5px 0px 15px;
        font-size: 21px;
        margin-bottom: 13px;
        margin-left: 9px;
        -webkit-appearance: none;
        font-family: 'Amatic SC', cursive;
        font-weight: 400;
    }
    .box-form{
        float:left;
        margin-top: 50px;
        width: 450px;
    }
    .button{
        background: url(../images/img_sprite.png) no-repeat -660px -338px;
        width: 100px;
        height: 49px;
        float: right;
        border: none;
        color: white;
        font-family: 'Amatic SC', cursive;
        font-weight: 400;
        font-size: 22px;
        margin-top: 5px;
    }
    .clear{
        clear: both;
        height: 2px;
    }
       .checkbox{
           float: left;
           margin-top: 10px;
           margin-right: 10px;
       }

</style>
<div class="box-fr">
  <div class="box-title">
    <h2>STAGE CONFIGURATION</h2>
  </div>
  <p>Change stage background.</p>
  <div class="box-form">
    <section class="td2 left" style="width:300px;margin-top: -42px;margin-left: 94px;">
      <label><span class="checkbox"><input name="stage[design]"  class="design" type="radio" value="4" <% if @stage.design.to_i == 4 %>checked="checked"<% end %>></span><%= image_tag('ec-4.png', :width => 160,:style => 'float: left;margin-bottom: 10px;') %> <button class="button">Change!</button></label>
      <section class="clear"></section>
      <label><span class="checkbox"><input name="stage[design]"  class="design" type="radio" value="1" <% if @stage.design.to_i == 1 %>checked="checked"<% end %>></span><%= image_tag('ec-1.png', :width => 160,:style => 'float: left;margin-bottom: 10px;') %> <button class="button">Change!</button></label>
      <section class="clear"></section>
      <label><span class="checkbox"><input name="stage[design]" class="design" type="radio" value="2" <% if @stage.design.to_i == 2 %>checked="checked"<% end %>></span><span class="brown"><%= image_tag('ec-2.png', :width => 160,:style => 'float: left;') %></span> <button class="button">Change!</button></label>
      <section class="clear" style="height: 20px;"></section>
      <% pool = 0 %>
      <% if !@stage_item.nil? %>
          <% @stage_item.each do |si| %>
              <% if si.item.to_i == 3 %>
                  <% pool = 1 %>
              <% end %>
          <% end %>
      <% end %>
      <% if pool == 0 %>
          <label><span class="checkbox"><input name="stage[design]" class="design" type="radio" value="3"></span><span class="brown"><%= image_tag('ec-3.png', :width => 160,:style => 'float: left;') %></span></label>
          <section class="clear" style="height: 20px;"></section>
      <% end %>
      <label><span class="checkbox"><input name="stage[design]" class="design" type="radio" value="0" <% if @stage.design.to_i == 0 %>checked="checked"<% end %>></span><span><strong>no design</strong></span>  <button class="button">Change!</button></label>

    </section>



  </div>


</div>

app/views/stages/featured_users.html.erb
<h3>Featured users</h3>
<% if !@tippers.nil? %>

    <% @tippers.each do |d| %>
        <%
           ch = Character.find(:all, :conditions => ['user_id = ?', d.sender])
           user = User.find(d.sender)

        %>

        <%
           if ch.count == 0
        %>
            <div class="featured" rel="<%= d.sender %>" name="<%= user.name %>">
              <div class="avatar preview avatar-head-1">
                <div class="avatar preview avatar-eyes-1"></div>
                <div class="avatar preview avatar-nose-1"></div>
                <div class="avatar preview avatar-mouth-1"></div>
              </div>
            </div>

        <% else %>
            <div class="featured" rel="<%= d.sender %>" name="<%= user.name %>">
              <% ch.each do |c| %>
                  <% dd = c.section.split('-') %>
                  <% if dd[1] == 'head' %>
                      <div class="avatar preview <%= c.section %>">
                        <% if dd[1] == 'head' %>
                            <% ch.each do |f| %>
                                <% dc = f.section.split('-') %>
                                <% if dc[1] == 'eyes' || dc[1] == 'nose' || dc[1] == 'mouth' %>
                                    <div class="avatar preview <%= f.section %>"></div>
                                <% end %>
                            <% end %>
                        <% end %>
                      </div>
                  <% end %>
              <% end %>
            </div>
        <% end %>
    <% end %>
<% end %>

app/views/stages/invitation.html.erb
<article id="container">
  <!-- start box -->
  <section class="box">
    <!-- start breadcrumb -->
    <section class="breadcrumb inner">
      <ul>
        <li class="first"><%= link_to(image_tag('ic_home.png'), root_path)  %></li>
        <li><a href="/stage/<%= @id %>"><%= @stage.room_name %></a></li>
      </ul>
      <section class="clear"></section>
    </section>
    <!-- end breadcrumb -->
    <!-- start register-form -->
    <section class="profile">
      <section class="rowline">
        <h2>Your Guest List</h2>
        <p style="font-size: 22px; font-weight: 400; font-family: 'Amatic SC', cursive;">You can send invitations to your followers and friends, please add their emails.</p>

        <div class="form_invitation">
           <input type="text" name="" placeholder="email" class="form-input-medio" id="email" style="float:left" />
           <input type="hidden" id="stage_id" value="<%= @stage.id %>"  />
           <input type="button" value="invite" class="button button-invitation" />

          <div class="list_invitation">
            <h2>Users list</h2>
            <ul>
              <%
                inv = Invitation.find(:all, :conditions => ['stage_id = ?', @stage.id])
                inv.each do |d|
              %>
              <li><%= d.user_id %></li>
              <% end %>

            </ul>
          </div>

        </div>




      </section>

    </section>

    <!-- end creative-block -->
    <section class="clear"></section>

  </section>
  <!-- end box -->
</article>

app/views/stages/makeStage.html.erb
<article id="container">
  <!-- start box -->
  <section class="box">
    <!-- start breadcrumb -->
    <section class="breadcrumb inner">
      <ul>
        <li class="first"> <%= link_to(image_tag('ic_home.png', :alt => 'home'),root_path, :title => 'Home') %></li>
        <li><%= link_to 'Create Performance', create_performance_path, :title => 'Create Performance' %></li>
      </ul>
      <section class="clear"></section>
    </section>
    <!-- end breadcrumb -->
    <!-- start register-form -->
    <%= form_tag("/stage/create", :method => "post", :class => 'register-form', :id => 'makeStage',:multipart => true)  do %>
        <section class="rowline">
          <h2>Create Performance</h2>
          <p>Its easy to start sharing your performances with the world. Just fill in the following forms and you’re ready to go.</p>
        </section>


        <%= text_field_tag("stage[room_name]",nil,:class => 'form-input-medio required', :placeholder => 'Room Name') %>
        <section class="rowline" style="margin: -29px 0px 16px 0px;">
          <section class="row">
            <section class="td1 left" style="width:200px; margin-left: 10px;">Start show right now</section>
            <section class="td2 left" style="width:200px;">
              <label><span class="checkbox"><input name="stage[shownow]"  class="shownow" type="radio" value="yes" checked="checked"></span>YES</label>
              <section class="clear"></section>
              <label><span class="checkbox"><input name="stage[shownow]" class="shownow" type="radio" value="no"></span><span class="brown">NO</span></label>
            </section>
            <section class="clear"></section>
          </section>
          <section class="row" style="margin-top:-28px;" id="livebox">
            <section class="td1 left" style="width:430px;">Time 'till live </br>
              <%=  datetime_select("stage", "live", :prompt => true) %>
            </section>
            <section class="clear"></section>
          </section>
        </section>
        <%= select_tag("stage[type]", options_for_select([ ['Public', 'public'], ['Private', 'private']]), :prompt => 'Type Performance', :class => 'form-input-select required') %>
        <%= select_tag("stage[type_ticket]", options_for_select([['Free', 'free'], ['Paid', 'paid']]), :prompt => 'Type Ticket', :class => 'form-input-select required') %>
        <%= text_field_tag("stage[ticket_price]",nil,:class => 'form-input-medio  required', :placeholder => 'Ticket Price') %>
        <%= select_tag("stage[limit_seats]", options_for_select([['Unlimited','Unlimited'],['1','1'],['10', '10'], ['20', '20'], ['30', '30'], ['50', '50'], ['100', '100'], ['120', '120'], ['160', '160'], ['200', '200']]), :prompt => 'Limited Seats', :class => 'form-input-select required') %>
        <%= file_field_tag 'stage[performance_image]', :class => 'upload' %>
        <%= text_field_tag 'stage[performance_image_fake]',nil, :class => 'form-input-file', :placeholder => 'Performance Image' %>
        <%= collection_select(:stage,:category_id, Category.all, :id, :name, {:prompt => 'Category'}, {:class => 'form-input-select required'}) %>
        <%#= select_tag("stage[sub_category_id]",options_for_select([['subcategorie 1', '1'], ['subcategorie 2', '2']]), :prompt => 'Sub Category', :class => 'form-input-select') %>
        <%= select_tag("stage[rate]", options_for_select([['General Audiences', 'general audiences'], ['Parental Guidance Suggested', 'parental guidance suggested'], ['Parents Strongly Cautioned', 'parents strongly cautioned'],['Restricted','restricted'],['No One 17 and Under Admitted','no one 17 and under admitted']]), :prompt => 'Content Rate', :class => 'form-input-select required') %>
         <%= collection_select(:stage,:language_content , Language.find(:all, :order => 'orden DESC'), :id, :name, {:prompt => 'Content Language'}, {:class => 'form-input-select required'}) %>



        <%# text_field_tag("stage[alive]",nil,:class => 'input', :placeholder => 'Time \'till live') %>
        <section class="rowline">
          <p class="condition"><input type="checkbox" name="condition" value="1" class="required" /> I have read the <a href="http://beta.theopenhat.com/pages/terms_&_conditions/modal" class="modaltc">terms & conditions</a></p>
        </section>

        <input type="hidden" name="stage[design]" id="stage_design" value="4" />
        <input name="submit" type="submit" value="Create" class="button">
    <% end %>
    <!-- end register-form -->
    <!-- start design-block -->
    <section class="design-block">
      <h3>Design your stage</h3>
      <p>Make your performance unique. Pimp your stage with our different designs. </p>
      <section class="rowline">
        <div class="form-information">
        <section class="row">
          <section class="td1 left" style="width:130px;">Design</section>
          <section class="td2 left" style="width:200px;">
            <label><span class="checkbox"><input name="stage[design]"  class="design" type="radio" value="4" checked="checked"></span><%= image_tag('ec-4.png', :width => 160,:style => 'float: right;margin-bottom: 10px;') %></label>
            <section class="clear"></section>
            <label><span class="checkbox"><input name="stage[design]"  class="design" type="radio" value="1" ></span><%= image_tag('ec-1.png', :width => 160,:style => 'float: right;margin-bottom: 10px;') %></label>
            <section class="clear"></section>
            <label><span class="checkbox"><input name="stage[design]" class="design" type="radio" value="2"></span><span class="brown"><%= image_tag('ec-2.png', :width => 160,:style => 'float: right;') %></span></label>
            <section class="clear" style="height: 20px;"></section>
            <% pool = 0 %>
            <% if !@stage_item.nil? %>
                <% @stage_item.each do |si| %>
                    <% if si.item.to_i == 3 %>
                        <% pool = 1 %>
                    <% end %>
                <% end %>
            <% end %>
            <% if pool == 1 %>
                <label><span class="checkbox"><input name="stage[design]" class="design" type="radio" value="3"></span><span class="brown"><%= image_tag('ec-3.png', :width => 160,:style => 'float: right;') %></span></label>
                <section class="clear" style="height: 20px;"></section>
            <% end %>
            <label><span class="checkbox"><input name="stage[design]" class="design" type="radio" value="0"></span><span><strong>no design</strong></span></label>
            <section class="clear"></section>
            <a href="/accounts_settings#tokens" style="margin-top: 20px;display:block;color:#D94601;">Buy more stage designs</a>
          </section>



        </section>
        </div>


      </section>
    </section>
    <!-- end design-block -->
    <section class="clear"></section>

  </section>
</article>

<script type="text/javascript">
  $(document).ready(function(){
      $('.design').click(function(){
            $('#stage_design').val($(this).val());
      });
  });
</script>

app/views/stages/noinvitation.html.erb
<article id="container">
  <!-- start box -->
  <section class="box">
    <!-- start breadcrumb -->
    <section class="breadcrumb inner">
      <ul>
        <li class="first"><%= link_to(image_tag('ic_home.png'), root_path)  %></li>
        <li><a href="#">No Invitation</a></li>
      </ul>
      <section class="clear"></section>
    </section>
    <!-- end breadcrumb -->
    <!-- start register-form -->
    <section class="profile">
      <section class="rowline">
        <h2 style="font-weight: 400;">Do you have an invitation?</h2>
        <p style="font-size: 60px; font-weight: 400; font-family: 'Amatic SC', cursive;margin-top: 26px;">An invitation is required to see this performance</p>


      </section>

    </section>

    <!-- end creative-block -->
    <section class="clear"></section>

  </section>
  <!-- end box -->
</article>

app/views/stages/report.html.erb
<link href="http://fonts.googleapis.com/css?family=Amatic+SC:400,700" media="all" rel="stylesheet" type="text/css">
<script type="text/javascript" src="/javascripts/jquery.min.js"></script>
<script type="text/javascript" >
    $(document).ready(function(){
        $('.button').click(function(){
            var request = $.ajax({
                type: "GET",
                url: "/savereport/<%= @id %>/"+$('.text').val()+"/<%= current_user.id %>",
                success: function(data){
                   alert('Report has been sent successfully');
                }
            });


            return false;
        });
    });
</script>
<style>
    .box-fr{
        font-family: 'Amatic SC', cursive;
        font-weight: 800;
    }
    .box-title{
        margin: 0 auto;
        width: 150px;
    }
    .box-title img{
        float: left;
        padding-right: 12px;
    }
    .box-title h2{
        font-size: 38px;
        line-height: 32px;
        margin-left: 12px;
    }
    p{
        font-size: 25px;
        margin: 0px auto;
        width: 440px;
    }

    p.text-tip{
        color: #D94601;
    }

    a.buy_more{
        color: #D94601;
    }
    .text{
        background: url('../images/sprite-forms.png') -17px -221px no-repeat;
        width: 339px;
        border: none;
        height: 62px;
        padding: 0px 5px 0px 15px;
        font-size: 21px;
        margin-bottom: 13px;
        margin-left: 9px;
        -webkit-appearance: none;
        font-family: 'Amatic SC', cursive;
        font-weight: 400;
    }
    .box-form{
        float:left;
        margin-top: 50px;
        width: 450px;
    }
    .button{
        background: url(../images/img_sprite.png) no-repeat -660px -338px;
        width: 100px;
        height: 49px;
        float: right;
        border: none;
        color: white;
        font-family: 'Amatic SC', cursive;
        font-weight: 400;
        font-size: 22px;
        margin-top: 5px;
    }
</style>
<div class="box-fr">
  <div class="box-title">
    <h2>REPORT USER</h2>
  </div>
  <p>Please select the category that most closely reflects your concern about the video, so that we can review it and determine whether it violates rules.</p>

  <div class="box-form">
    <select class="text">
      <option>select reason</option>
      <option value="sexual content">sexual content</option>
      <option value="violent and repulsive content">violent content and repulsive</option>
      <option value="discriminatory or abusive content">discriminatory or abusive content</option>
    </select>

    <button class="button">Report!</button>

  </div>


</div>