config/routes.rb
Openhat::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users ,  :controllers => { :registrations => 'registrations' } do
    get "/register"   => "registrations#new",   :as => :new_user_registration
    get "/login", :to => "devise/sessions#new"
  end

  match 'profile' => 'home#profile', :as => 'profile'
  match 'profile/:id' => 'home#public_profile', :as => 'public_profile'
  match 'profile_modal/:id' => 'home#public_profile_modal', :as => 'public_profile_modal'
  match 'accounts_settings' => 'home#accounts_settings', :as => 'accounts_settings'
  match 'follow/:id' => 'home#follow', :as => 'follow'
  match 'unfollow/:id' => 'home#unfollow', :as => 'unfollow'
  match 'messages' => 'messages#index', :as => 'messages'
  match 'messages/new.:format' => 'messages#user_ajax'
  match 'message/send' => 'messages#sendto', :via => "post"
  match 'message/send_m' => 'messages#send_m', :via => "post"
  match 'stage/create' => 'stages#create', :via => "post"
  match 'message_new' => 'messages#new', :as => 'message_new'
  match 'message/:id' => 'messages#read', :as => 'message_read'
  match 'avatar/maker' => 'avatars#index', :as => 'avatar_maker'
  match 'avatar/getSections/:id' => 'avatars#getSections'
  match 'avatar/getSectionUrl/:id' => 'avatars#getSectionUrl'
  match 'create_performance' => 'stages#makeStage', :as => 'create_performance'
  match 'stage' => 'stages#index'
  match 'stage/:id' => 'stages#index', :as => 'stage'
  match 'stage2/:id' => 'stages#index2', :as => 'stage2'
  match 'category/:id' => 'categories#index', :as => 'category'
  match 'all' => 'categories#all', :as => 'all'
  match '/pages/:page' => "pages#page", :as => 'pages'
  match '/pages/:page/modal' => "pages#modal", :as => 'page_modal'
  match 'buy_tokens' => "tokens#buy", :as => 'buy_tokens'
  match 'buy_show' => "tokens#show"
  match 'buy_cancel' => "tokens#cancel"
  match 'send_tips/:id/:stage'  => "tokens#send_tips", :as => 'send_tips'
  match 'send_heckle'  => "tokens#send_heckle", :as => 'send_heckle'
  match 'sendtip' => "tokens#sendtip"
  match 'changeimage' => "home#changeimage"
  match 'report/:id' => "stages#report"
  match 'share/:id' => "home#share"
  match 'close/:id' => "stages#close"
  match 'configuration/:id' => "stages#configuration"
  match 'saveconfiguration/:id/:option' => "stages#saveconfiguration"
  match 'tippers/:id' => 'stages#tippers'
  match 'totaltips/:id' => 'stages#totaltips'
  match 'savecharacter' => "home#savecharacter", :as => 'savecharacter', :via => 'post'
  match 'saveinformation' => "home#saveinformation", :as => 'saveinformation', :via => 'post'
  match 'saveprivacy' => "home#saveprivacy", :as => 'saveprivacy', :via => 'post'

  match 'saveimage' => "home#saveimage", :as => 'saveimage', :via => 'post'

  match 'savereport/:id/:report/:sender' => 'stages#savereport', :as => 'savereport'
  match 'buy/:heckle/:tokens/:amount' => "tokens#buytokens"
  match 'buystage/:stage/:item/:tokens' => "tokens#buystages"
  match 'discountHeckle/:heckle' => 'tokens#discountHeckle'
  match 'beta' => 'home#beta'
  match 'contact' => "pages#contact", :as => 'contact', :via => 'post'

  match 'shop_add' => 'shopping#add', :as => 'shop_add', :via => 'post'
  match 'cashout' => 'home#cashout'

  match  'performance_update/:id' => 'stages#performance_update'
  match 'send_cashout/:user/:tokens' => 'home#send_cashout'
  match 'featured_users/:id' => 'stages#featured_users'
  match 'payment/notify' => 'tokens#notify', :via => 'post'
  match 'noinvitation' => 'stages#noinvitation', :as => 'noinvitation'
  match 'invitation/:id' => 'stages#invitation', :as => 'invitation'
  match 'add_invitation/:id/:email' => 'stages#add_invitation', :email => /.*/
  match 'noticket' => 'stages#noticket', :as => 'noticket'
  match 'notification' => 'messages#notification'
  root :to => 'home#index'

  match 'shopping_cart' => 'shopping#shopping_cart'
  match 'upload_dropbox' => 'home#upload_dropbox'











end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :artist, :description, :event_id, :type, :user_id
  # type  ---- call, tokens, buy, watch
  
end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
  attr_accessible :gender, :user_id
end

app/models/billing.rb
class Billing < ActiveRecord::Base
  attr_accessible :account, :address, :city, :country, :state, :user_id, :zip
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :state
  has_many :sub_categories, :dependent => :destroy
  validates :name, :presence => true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :message, :name, :rate, :subject
end

app/models/message.rb
class Message < ActiveRecord::Base
  #belongs_to :user,  :foreign_key => 'sender'
  #belongs_to :user,  :foreign_key => 'recipient'
  #attr_accessible :body, :recipient, :sender
  belongs_to :yarn
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :token_id, :user_id
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :title, :url
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  attr_accessible :business, :first_name, :invoice, :item_name, :item_number, :last_name, :mc_currency, :mc_fee, :payer_email, :payer_id, :payment_date, :payment_fee, :payment_gross, :payment_status, :payment_type, :quantity, :residence_country
end

app/models/privacy.rb
class Privacy < ActiveRecord::Base
  attr_accessible :option1, :option2, :option3, :option4, :option5, :option6, :user_id
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price, :user_id
  belongs_to :user
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  attr_accessible :performer, :rate, :user_id
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :reason, :stage, :user_id
end

app/models/section.rb
class Section < ActiveRecord::Base
  attr_accessible :free, :gender, :group, :img_back, :img_front, :name, :parent
  has_attached_file :img_back, :styles => {:thumb => { :geometry => '92x92>', :quality => 50}}
  has_attached_file :img_front, :styles => {:thumb => { :geometry => '92x92>', :quality => 50}}
end

app/models/stage.rb
class Stage < ActiveRecord::Base
  attr_accessible :category_id, :language_content, :rate, :room_name, :status, :sub_category_id, :type
  has_attached_file :image, :styles => {:thumb => { :geometry => '241x175>', :quality => 50}},:path => ":rails_root/public/images/stages/:style/:id/:filename", :url => "/images/stages/:style/:id/:filename"
  belongs_to :user
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :price, :stage_id, :user_id
end

app/models/tip.rb
class Tip < ActiveRecord::Base
  attr_accessible :receiver, :sender, :tokens
end

app/models/token.rb
class Token < ActiveRecord::Base
  attr_accessible :name, :price, :quantity, :status
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_many :authentications 
  has_many :followers
  
  has_many :messages
  has_many :categories
  has_many :stages
  has_many :products
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :about, :image, :name, :gender, :interest, :hometown, :birthdate ,:image_fb
  has_attached_file :image, :styles => {:thumb => { :geometry => '75x75>', :quality => 50},:normal => { :geometry => '298x350>', :quality => 50}, :profile => { :geometry => '298x350>', :quality => 50}},:path => "/users/:style/:id/:filename"

  def apply_omniauth(omniauth)
    self.email = omniauth['info']['email'] if email.blank?
    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
  end
  def password_required?  
    (authentications.empty? || !password.blank?) && super  
  end
end

app/models/yarn.rb
class Yarn < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>THE OPEN HAT</title>
	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
  <%= stylesheet_link_tag    'style', 'css3','colorbox','avatar','heads','http://fonts.googleapis.com/css?family=Amatic+SC:400,700',:media => "all" %>
  <%= javascript_include_tag 'jquery.min','jquery_ujs','jquery-ui', 'jquery.cycle', 'jquery.colorbox' ,'jquery.path','jquery.transit.min', 'jquery.validate.min.js', 'additional-methods.min.js', 'jquery.raty.min.js', 'modernizr.js', 'flash.detect.js', 'application' %>
  <script src="/javascripts/swfobject.js" type="text/javascript"></script>
  <%= csrf_meta_tags %>
  <meta name="title" content="TheOpenHat" />
  <meta name="description" content="The online platform that brings performers and audiences together" />
</head>
<body>

    <script type="text/javascript">
        setInterval("notification()",10000);
    </script>

    <%#= current_user.sign_in_count %>
	<!-- start box -->
	<section class="box">
		<!-- start header -->
	    <header id="header">
	    	<!-- start logo -->
	        <section id="logo">
	        	<h1><%= link_to( image_tag('logo.png', :width => 408, :height => 74, :alt => 'THE OPEN HAT'), root_path, :title => 'THE OPEN HAT')%></h1>
	        </section>
	        <!-- end logo -->
	        <!-- start header right -->
	
			<% if user_signed_in? %>
              <% a = Character.find(:all, :conditions => ['user_id = ?', current_user.id]) %>
			<section class="Account">
	        	<section class="img-frame">&nbsp;</section>

              <div class="thumb">
                <%
                   if a.count == 0
                %>
                    <div class="avatar preview avatar-head-1">
                      <div class="avatar preview avatar-eyes-1"></div>
                      <div class="avatar preview avatar-nose-1"></div>
                      <div class="avatar preview avatar-mouth-1"></div>
                    </div>
                    <div class="avatar preview avatar-jacket-1"></div>


                <% else %>

                    <% a.each do |d| %>
                        <% dd = d.section.split('-') %>
                        <% if dd[1] == 'head' || dd[1] == 'jacket' %>
                            <div class="avatar preview <%= d.section %>">
                              <% if dd[1] == 'head' %>
                                  <% a.each do |c| %>
                                      <% dc = c.section.split('-') %>
                                      <% if dc[1] == 'eyes' || dc[1] == 'nose' || dc[1] == 'mouth' %>
                                          <div class="avatar preview <%= c.section %>"></div>
                                      <% end %>
                                  <% end %>
                              <% end %>
                            </div>
                        <% end %>
                    <% end %>

                <% end %>
              </div>

                <span class="back-avatar-hover"></span>
                <span class="avatar-hover">
                     <%= link_to "EDIT PROFILE", accounts_settings_path, :title => 'Edit Profile' %>
                     <%= link_to "MESSAGES(0)", messages_path, :id => 'messanges' %>
                     <%= link_to "BUY TOKENS", '/accounts_settings#tokens' %>
                     <%= link_to "LOGOUT (X)", destroy_user_session_path, :method => :delete, :class => "logout" %>
                </span>

	            <section class="info">
	            	<h2>Hi <span><%= current_user.name %></span></h2>
	                <span class="link"><%= link_to 'My profile', profile_path, :title => 'My profile'%> / <%= link_to "Account settings", accounts_settings_path, :title => 'Account settings' %> / 
                    
                    <a href="/shopping_cart/">My Cart (<%= (session[:shopping_cart].nil?)? "0" : session[:shopping_cart].length.to_s %>)</a>

                    </span>
	            </section>
	        </section>
			<% else %>
	        <section id="header-right">
	        		<%= link_to 'Login',  '/auth/facebook', :class => 'button', :title => 'Login'%>
			
				
	        	<ul>
	            	<li><%= link_to 'Login', login_path, :title => 'Login' %></li>
	                <li><%= link_to 'Register', new_user_registration_path, :title => 'Register' %></li>
	            </ul>
	        </section>
			<% end %>
	        <!-- end header right -->
	        <section class="clear"></section>
	        <!-- start navigation -->
	        <nav id="navigation">
	        	<ul>
	            	<li>HUBS:</li>
					<% Category.find(:all).each do |e| %>
						<li class="item-menu"><%= link_to e.name, category_path(e.name.downcase), :title => e.name %>

                        </li>
					<% end %>

	                <li class="last"><a href="#" title="Rss">rss</a></li>
                    <% if !current_user.nil? %>
                      <% stage = Stage.find(:first, :conditions => ['user_id = ? and delete_status = 0', current_user.id]) %>
                      <% if stage.nil? %>
                      <li class="new"><a href="/create_performance" title="Create Stage" class="btn-newstage"></a></li>
                      <% end %>
                    <% end %>
	            </ul>
	        </nav>
	        <!-- end navigation -->
	    </header>
	    <!-- end header -->
	    <section class="clear"></section>
</section>

        <section class="box alerts">
           <!-- <%# if !flash[:notice].blank? %>
            <div class="notice">
                 <%#= flash[:notice] %>
            </div>
            <%# end %> -->
          <% if session[:save] %>
              <div class="warning">
                <a class="close" href="#">X</a>
                <p><%=  session[:save] %></p>
              </div>
              <% session[:save] = nil %>
          <% end %>
            <% if current_user %>
                  <%
                     gift = MyToken.find(:first, :conditions => ['user_id = ? AND description = "initial gift"', current_user.id])

                     if gift.nil?
                       element = ElementStage.new
                       element.types = 'flower'
                       element.user_id = current_user.id
                       element.amount = 200
                       element.save!

                       element = ElementStage.new
                       element.types = 'tomato'
                       element.user_id = current_user.id
                       element.amount = 200
                       element.save!

                       g = MyToken.new
                       g.amount = 0
                       g.user_id = current_user.id
                       g.operation = '-'
                       g.description  = 'initial gift'
                       g.save!
                     end
                  %>

                  <%

                   if !stage.nil?
                     if controller_name == "home" && action_name == "index"
                %>
                  <div class="warning">
                        <a class="close" href="#">X</a>
                        <p>You have a stage running with 0 online viewers, please click <a href="/stage/<%=  Digest::MD5.hexdigest(stage.id.to_s)[0,11] %>">here</a> to start performing or click <a href="#<%=  Digest::MD5.hexdigest(stage.id.to_s)[0,11] %>" id="closeStage">here</a> to close your stage.</p>
                       <!--<p>You have a performance programed at "<%= stage.live.strftime('%Y/%m/%d %H:%M') %>", that's in "<%= ((stage.live - DateTime.now)/ 1.hour).round  %> hours". Click <%= link_to 'here', stage_path(Digest::MD5.hexdigest(stage.id.to_s)) %> to go to you're stage.</p> -->
                  </div>
                <%
                       end
                   end
                   if session[:warn_profile].nil?
                   current_state = 0
                   if !current_user.name.blank?
                      current_state += 25
                   end
                   if !current_user.about.blank?
                     current_state += 25
                   end
                   if !current_user.image.blank?
                     current_state += 25
                   end

                   if a.count != 0
                      current_state += 25
                   end

                   if current_state < 100
                %>
                   <div class="warning">
                     <a class="close" href="#">X</a>
                     <p>You're profile is <%= current_state %>% complete, <% if a.count == 0 %>You have not created your avatar, click <%= link_to 'here', '/accounts_settings#create_your_character'  %> for make you avatar or<% end %>  please click <%= link_to 'here','/accounts_settings#user_information' %> to add more information.</p>
                   </div>
                    <% session[:warn_profile] = '1' %>
                <% end  %>
                  <% end %>
            <% end %>
            <% if session[:error] %>
              <div class="warning">
                <a class="close" href="#">X</a>
                <p><%= session[:error].html_safe %></p>
              </div>
                <% session[:error] = nil %>
            <% end %>
        </section>

			<%= yield %>
			
			<section class="clear"></section>
<!-- start footer -->
<footer id="footer">
	<!-- start box -->
    <section class="box">
    	<!-- start footer top -->
        <section id="footer-top">
            <!-- start footer link -->
            <nav class="footer-link">
                <h5>Learn About Us</h5>
                <ul>
                    <li><%= link_to 'Contact', pages_path('contact'), :title => "Contact" %></li>
                    <li><%= link_to 'About Us', pages_path('about_us'), :title => "About Us" %></li>
                    <li><%= link_to 'Media Kit', pages_path('media_kit'), :title => "Media Kit" %></li>
                    <li><%= link_to 'Advertise', pages_path('advertise'), :title => "Advertise" %></li>
                    <li><%= link_to 'Terms & Conditions', pages_path('terms_&_conditions'), :title => "Terms & Conditions" %></li>
                    <li><%= link_to 'Privacy Policy', pages_path('privacy_policy'), :title => "Privacy Policy" %></li>
                </ul>
            </nav>
            <!-- end footer link -->
            <!-- start footer link -->
            <nav class="footer-link">
                <h5>Get help</h5>
                <ul>
                    <li><%= link_to 'FAQ', pages_path('faq'), :title => "FAQ" %></li>
                    <li><%= link_to 'Website Support', pages_path('website_support'), :title => "Website Support" %></li>
                    <li><%= link_to 'iPhone Support', pages_path('iphone_support'), :title => "iPhone Support" %></li>
                    <li><%= link_to 'System Status', pages_path('system_status'), :title => "System Status" %></li>
                </ul>
            </nav>
            <!-- end footer link -->
            <!-- start search -->
            <form action="#" class="search">
                <input type="text" name="field" value="Search" class="input" onfocus="if(this.value == 'Search') { this.value = ''; }" onblur="if(this.value == '') { this.value = 'Search'; }" />
                <input name="submit" type="submit" value="" class="button" />
            </form>
            <!-- end search -->
        </section>
        <!-- end footer top -->
        <!-- start footer mid -->
        <section id="footer-mid">
        	<span>All Material Copyright &copy; 2009-2012 The Main Stage INC. All music and performing arts &copy;</span>
        </section>
        <!-- end footer mid -->
    </section>
    <!-- end box -->
  <!-- start footer bottom -->
  <% if controller_name == "stages" && action_name == "index" %>
  <section id="footer-bot">
    <!-- start box -->
      <!-- start chat-block -->
      <section class="chat-block">

      </section>
      <!-- end chat-block -->
      <ul class="list1">
        <li><a href="#" class="globalchat" title="Global Chat"><%= image_tag 'ic_chat3.png', :alt => "chat" %>Global Chat</a></li>
        <div class="line-bar"></div>
        <li>Your chats</li>
      </ul>

    <!-- end box -->
  </section>
  <!-- end footer bottom -->


  <% end %>
</footer>
    <% if controller_name == "stages" && action_name == "index" %>
    <div class="shadown-left"></div>
    <div class="shadown-top"></div>
        <div class="shadown-layer">
        </div>
    <div class="shadown-right"></div>
        <div class="shadown-bottom"></div>
    <% end %>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-37121232-1']);
        _gaq.push(['_setDomainName', 'theopenhat.com']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
<!-- end footer -->
</body>
</html>

app/views/pages/modal.html.erb
<link href="http://fonts.googleapis.com/css?family=Amatic+SC:400,700" media="all" rel="stylesheet" type="text/css">
<style>
    .box-fr{
        font-family: 'Amatic SC', cursive;
        font-weight: 800;
    }
    .box-title{
        margin: 0 auto;
        width: 150px;
    }
    .box-title img{
        float: left;
        padding-right: 12px;
    }
    .box-title h2{
        font-size: 38px;
        line-height: 32px;
        margin-left: 12px;
    }
    p{
        font-size: 25px;
        margin: 0px auto;
        width: 440px;
    }
</style>
<div class="box-fr">
  <div class="box-title">
    <h2><%= @page.title %></h2>
  </div>
  <%= @page.content.html_safe %>


</div>

app/views/pages/page.html.erb
<article id="container">
<!-- start box -->
<section class="box">
<!-- start breadcrumb -->
<section class="breadcrumb inner">
  <ul>
    <li class="first"><%= link_to(image_tag('ic_home.png'), root_path)  %></li>
    <li><%= link_to @page.title, pages_path(@page.title.gsub(" ", "_").downcase), :title => @page.title %></li>
  </ul>
  <section class="clear"></section>
</section>
<!-- end breadcrumb -->
<!-- start register-form -->
<section class="profile">
  <section class="rowline">
    <h2><%= @page.title %></h2>
    <%= @page.content.html_safe %>
    <% if @page.title == 'Contact' %>
        <%= form_tag("/contact", :method => "post", :class => 'form-information', :id => 'form-user-information')  do %>
        <section class="rowline">
          <section class="row">
            <section class="td1 left">Name:</section>
            <section class="td2 left">
              <input type="text" id="contact_name" name="contact[name]"  style="margin-left: 2px;" class="form-input-medio"  />

            </section>
            <section class="clear"></section>
          </section>
          <section class="row">
            <section class="td1 left">Email:</section>
            <section class="td2 left">
              <input type="text" id="contact_email" name="contact[email]"  style="margin-left: 2px;" class="form-input-medio"  />

            </section>
            <section class="clear"></section>
          </section>
          <section class="row">
            <section class="td1 left">Rate your experience:</section>
            <section class="td2 left">
              <select class="form-input-select" id="contact_rate" name="contact[rate]" style="margin-left: 2px;">
                <option>Select Rate</option>
                <option value="Awful">Awful</option>
                <option value="Regular">Regular</option>
                <option value="Great">Great</option>
                <option value="Best-idea-ever!">Best-idea-ever!</option>
              </select>
            </section>
            <section class="clear"></section>
          </section>
          <section class="row">
            <section class="td1 left">Subject:</section>
            <section class="td2 left">
              <select class="form-input-select" id="contact_subject" name="contact[subject]" style="margin-left: 2px;">
                <option>Select Subject</option>
                <option value="General Inquiry">General Inquiry</option>
                <option value="Bug Report">Bug Report</option>
                <option value="Beta Tester">Beta Tester</option>
                <option value="Complaint">Complaint</option>
              </select>
            </section>
            <section class="clear"></section>
          </section>


          <section class="row">
            <section class="td1 left">Message:</section>
            <section class="td2 left">
              <textarea id="contact_message" name="contact[message]" class="form-textarea" ></textarea>
            </section>
            <section class="clear"></section>
          </section>



        </section>
        <% end %>
        <section class="creative-block">
          <section class="clear"></section>

          <a href="#" class="button button2" title="Submit" onclick="document.getElementById('form-user-information').submit();">Submit</a>
        </section>

    <% end %>
  </section>

</section>

<!-- end creative-block -->
<section class="clear"></section>
  <% if !@performance_random.nil? %>
      <!-- start bottom-link -->

      <nav class="bottom-link">
        <ul>
          <li>random performers:</li>
          <% countRandom = 1 %>
          <%  @performance_random.each do |rp| %>
              <li><a href="/profile/<%= Digest::MD5.hexdigest(rp.user_id.to_s) %>" title="<%= rp.user.name %>"><%= rp.user.name %></a></li>
              <% if @performance_random.count !=  countRandom %>
                  <li>/</li>
              <% end %>
              <% countRandom = countRandom + 1 %>
          <% end %>
        </ul>
        <section class="clear"></section>
      </nav>
      <!-- end bottom-link -->
  <% end %>
</section>
<!-- end box -->
</article>